### ISSUE TITLE
Template mod (and mods based on it) crash on startup on macOS, despite Quilt Launcher working in MultiMC

### ISSUE THREAD

**Issue by rinOfTheStars** [QuiltMC/quilt-example-mod#6]
See here for the crash's latest.log: https://paste.ee/p/2vuJu
Dev environment is running on Intelij IDEA 2022.1, and on ARM64 macOS Java 17

Of most note is probably this:
```[02:32:51] [main/ERROR] (Quilt Loader) Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.util.Identifier net.minecraft.util.registry.RegistryKey.method_29177()'
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.16.0-beta.10.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.0-beta.10.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28) [quilt-loader-0.16.0-beta.10.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23) [quilt-loader-0.16.0-beta.10.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

Crashes for both Client and Server launch. I checked a fabric project I have installed and it still works, so it's not an issue with IDEA or Java, seemingly.
Not sure if this is a Quilt Loader issue or a Example Mod issue, but I've not seen any other reports of it so I've put it here

**Comment by rinOfTheStars** [comment]
Gradle was being Utterly Cursed again and caused this issue
you gotta love it /s
